// bsuir-lab1.cpp : This file contains the 'main' function. Program execution begins and ends there.
//


#include <iostream>
#include <random>

struct tstk1
{
	int inf;
	tstk1* a;
};

tstk1* push(tstk1* sp, int inf)
{
	tstk1* spt = new tstk1;
	spt->inf = inf;
	spt->a = sp;
	return spt;
}

tstk1* pop(tstk1* sp, int& inf)
{
	if (sp == NULL) return NULL;

	tstk1* spt = sp;
	inf = sp->inf;
	sp = sp->a;
	delete spt;
	return sp;
}

tstk1* clear(tstk1* sp)
{
	tstk1* spt; int inf;

	while (sp != NULL)
	{
		spt = sp;
		inf = sp->inf;
		// std::cout << inf << std::endl;
		sp = sp->a;
		delete spt;
	}

	return NULL;
}

tstk1* createRandomStack(int size)
{
	std::random_device rd;  //Will be used to obtain a seed for the random number engine
	std::mt19937_64 gen(rd()); //Standard mersenne_twister_engine seeded with rd()
	std::uniform_int_distribution<int> dis(-50, 50);

	tstk1* spt = NULL;
	int inf = NULL;
	for (int n = 0; n < size; ++n) {
		// Use dis to transform the random unsigned int generated by gen into a
		// double in [1, 2). Each call to dis(gen) generates a new random double

		inf = dis(gen);
		// std::cout << inf << ' ';
		spt = push(spt, inf);

	}
	std::cout << std::endl;

	return spt;
}

tstk1* createPositiveStack(tstk1* sp)
{
	tstk1* positiveSp = NULL;
	tstk1* spt = sp;
	while (spt != NULL)
	{
		if (spt->inf > -1)
		{
			positiveSp = push(positiveSp, spt->inf);
		}
		spt = spt->a;
	}
	return positiveSp;
}

tstk1* createNegativeStack(tstk1* sp)
{
	tstk1* negativeSp = NULL;
	tstk1* spt = sp;
	while (spt != NULL)
	{
		if (spt->inf < 0)
		{
			negativeSp = push(negativeSp, spt->inf);
		}
		spt = spt->a;
	}
	return negativeSp;
}

void writeStack(tstk1* sp)
{
	std::cout << "stack values " << std::endl;
	tstk1* spt = sp;
	while (spt != NULL)
	{
		std::cout << spt->inf << ' ';
		spt = spt->a;
	}
	std::cout << std::endl << std::endl;
}

int main()
{
	tstk1* randomStack = createRandomStack(10);
	tstk1* positiveStack = createPositiveStack(randomStack);
	tstk1* negativeStack = createNegativeStack(randomStack);

	writeStack(randomStack);
	writeStack(positiveStack);
	writeStack(negativeStack);
}